const COURSE_ADMIN_CONFIG={url:'https://bcvtkdehflmqiyvloyiy.supabase.co',key:'sb_publishable_KgISTJ7-YKktjQXw3u0yuQ_KG6H1bFa'};
const courseSb=window.supabase?.createClient(COURSE_ADMIN_CONFIG.url,COURSE_ADMIN_CONFIG.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const C=(s,r=document)=>r.querySelector(s),CC=(s,r=document)=>[...r.querySelectorAll(s)];
let courses=[],lessons=[],currentCourse=null,editingLesson=null;
function cEsc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function slugify(v){return String(v||'').trim().toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,96)}
function showCourseLogin(message=''){C('#courseAdminApp')?.classList.add('hidden');C('#courseAdminLogin')?.classList.remove('hidden');if(C('#courseAdminLoginMessage'))C('#courseAdminLoginMessage').textContent=message}
async function checkCourseAdmin(){
  if(!courseSb)return false;const{data:{session}}=await courseSb.auth.getSession();if(!session){showCourseLogin();return false}
  const{data,error}=await courseSb.from('admin_users').select('role').eq('user_id',session.user.id).maybeSingle();
  if(error||!data){await courseSb.auth.signOut();showCourseLogin('This account is not authorized for Nexora Admin.');return false}
  C('#courseAdminIdentity').textContent=`${session.user.email||'Admin'} · ${data.role}`;C('#courseAdminLogin')?.classList.add('hidden');C('#courseAdminApp')?.classList.remove('hidden');await loadCourseAdmin();return true
}
C('#courseAdminLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();const msg=C('#courseAdminLoginMessage');if(msg)msg.textContent='Signing in…';const{error}=await courseSb.auth.signInWithPassword({email:C('#courseAdminEmail').value.trim(),password:C('#courseAdminPassword').value});if(error){msg.textContent=error.message;return}await checkCourseAdmin()});
C('#courseAdminLogout')?.addEventListener('click',async()=>{await courseSb.auth.signOut();location.reload()});
async function loadCourseAdmin(){
  const[c,l]=await Promise.all([courseSb.from('nexora_courses').select('*').order('sort_order',{ascending:true}),courseSb.from('nexora_lessons').select('*').order('sort_order',{ascending:true})]);
  if(c.error||l.error){C('#courseMessage').textContent=(c.error||l.error).message;return}courses=c.data||[];lessons=l.data||[];renderCourseList();if(currentCourse){currentCourse=courses.find(x=>x.id===currentCourse.id)||null;if(currentCourse)selectCourse(currentCourse.id);else clearCourseEditor()}
}
function renderCourseList(){const root=C('#courseAdminList');if(!root)return;root.innerHTML=courses.length?courses.map(x=>`<button class="course-admin-item ${currentCourse?.id===x.id?'active':''}" data-course-id="${cEsc(x.id)}"><strong>${cEsc(x.title)}</strong><span>${cEsc(x.track)} · ${lessons.filter(l=>l.course_id===x.id).length} lessons · ${x.is_active?'Active':'Hidden'}</span></button>`).join(''):'<div class="course-admin-empty">No courses yet.</div>';CC('[data-course-id]',root).forEach(b=>b.addEventListener('click',()=>selectCourse(b.dataset.courseId)))}
function selectCourse(id){currentCourse=courses.find(x=>x.id===id)||null;if(!currentCourse)return;C('#courseEditorEmpty').classList.add('hidden');C('#courseEditor').classList.remove('hidden');C('#courseEditorTitle').textContent=currentCourse.title;C('#courseId').value=currentCourse.id;C('#courseId').disabled=true;C('#courseTrack').value=currentCourse.track||'';C('#courseTitle').value=currentCourse.title||'';C('#courseLevel').value=currentCourse.level||'All levels';C('#courseSort').value=currentCourse.sort_order??100;C('#courseImage').value=currentCourse.image_url||'';C('#courseDescription').value=currentCourse.description||'';C('#courseActive').value=String(currentCourse.is_active);C('#courseMessage').textContent='';renderCourseList();renderLessonList()}
function clearCourseEditor(){currentCourse=null;C('#courseEditor').classList.add('hidden');C('#courseEditorEmpty').classList.remove('hidden');C('#courseEditorTitle').textContent='Select a course';renderCourseList()}
C('#newCourse')?.addEventListener('click',()=>{currentCourse={id:'',title:'',track:'Track',description:'',level:'All levels',image_url:'',is_active:true,sort_order:100,__new:true};C('#courseEditorEmpty').classList.add('hidden');C('#courseEditor').classList.remove('hidden');C('#courseEditorTitle').textContent='New course';C('#courseId').disabled=false;['courseId','courseTitle','courseImage','courseDescription'].forEach(id=>C('#'+id).value='');C('#courseTrack').value='Track';C('#courseLevel').value='All levels';C('#courseSort').value=100;C('#courseActive').value='true';C('#lessonAdminList').innerHTML='<div class="course-admin-empty">Save the course before adding lessons.</div>';C('#courseMessage').textContent=''});
C('#saveCourse')?.addEventListener('click',async()=>{const msg=C('#courseMessage'),title=C('#courseTitle').value.trim(),id=slugify(C('#courseId').value||title);if(title.length<2||id.length<2){msg.textContent='Add a course title and ID.';return}const row={id,title,track:C('#courseTrack').value.trim()||'Creator Academy',description:C('#courseDescription').value.trim(),level:C('#courseLevel').value,image_url:C('#courseImage').value.trim(),is_active:C('#courseActive').value==='true',sort_order:Math.max(0,Number(C('#courseSort').value)||100),updated_at:new Date().toISOString()};let error;if(currentCourse?.__new){({error}=await courseSb.from('nexora_courses').insert(row))}else if(currentCourse){const update={...row};delete update.id;({error}=await courseSb.from('nexora_courses').update(update).eq('id',currentCourse.id))}else return;if(error){msg.textContent=error.message;return}msg.textContent='Course saved ✓';currentCourse={...row};await loadCourseAdmin();selectCourse(id)});
C('#deleteCourse')?.addEventListener('click',async()=>{if(!currentCourse||currentCourse.__new)return;if(!confirm(`Delete “${currentCourse.title}” and all of its lessons?`))return;const{error}=await courseSb.from('nexora_courses').delete().eq('id',currentCourse.id);if(error){C('#courseMessage').textContent=error.message;return}clearCourseEditor();await loadCourseAdmin()});
function renderLessonList(){const root=C('#lessonAdminList');if(!root||!currentCourse)return;const rows=lessons.filter(l=>l.course_id===currentCourse.id).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));root.innerHTML=rows.length?rows.map(l=>`<div class="lesson-admin-row"><div><strong>${cEsc(l.title)}</strong><small>${cEsc(l.slug)} · ${cEsc(l.duration_minutes)} min · ${l.is_active?'Active':'Hidden'}</small></div><span class="preview">${l.is_preview?'PREVIEW':'FULL'}</span><button data-lesson-id="${l.id}">Edit</button></div>`).join(''):'<div class="course-admin-empty">No lessons in this course yet.</div>';CC('[data-lesson-id]',root).forEach(b=>b.addEventListener('click',()=>openLesson(lessons.find(l=>String(l.id)===b.dataset.lessonId))))}
function openLesson(l=null){if(!currentCourse||currentCourse.__new){C('#courseMessage').textContent='Save the course first.';return}editingLesson=l||null;C('#lessonEditorTitle').textContent=l?'Edit lesson':'New lesson';C('#lessonSlug').value=l?.slug||'';C('#lessonTitle').value=l?.title||'';C('#lessonDuration').value=l?.duration_minutes??10;C('#lessonSort').value=l?.sort_order??100;C('#lessonPreview').value=String(l?.is_preview??false);C('#lessonActive').value=String(l?.is_active??true);C('#lessonVideo').value=l?.video_url||'';C('#lessonSummary').value=l?.summary||'';C('#lessonText').value=l?.lesson_text||'';C('#lessonTask').value=l?.task_text||'';C('#lessonMessage').textContent='';C('#deleteLesson').classList.toggle('hidden',!l);C('#lessonEditor').classList.remove('hidden')}
function closeLesson(){C('#lessonEditor').classList.add('hidden');editingLesson=null}C('#newLesson')?.addEventListener('click',()=>openLesson());C('#lessonEditorClose')?.addEventListener('click',closeLesson);C('#cancelLesson')?.addEventListener('click',closeLesson);C('#lessonEditor')?.addEventListener('click',e=>{if(e.target===C('#lessonEditor'))closeLesson()});
C('#saveLesson')?.addEventListener('click',async()=>{if(!currentCourse||currentCourse.__new)return;const msg=C('#lessonMessage'),title=C('#lessonTitle').value.trim(),slug=slugify(C('#lessonSlug').value||title);if(title.length<2||slug.length<2){msg.textContent='Add a lesson title and slug.';return}const row={course_id:currentCourse.id,slug,title,summary:C('#lessonSummary').value.trim(),lesson_text:C('#lessonText').value.trim(),task_text:C('#lessonTask').value.trim(),video_url:C('#lessonVideo').value.trim(),duration_minutes:Math.max(1,Number(C('#lessonDuration').value)||10),is_preview:C('#lessonPreview').value==='true',is_active:C('#lessonActive').value==='true',sort_order:Math.max(0,Number(C('#lessonSort').value)||100),updated_at:new Date().toISOString()};let error;if(editingLesson){({error}=await courseSb.from('nexora_lessons').update(row).eq('id',editingLesson.id))}else{({error}=await courseSb.from('nexora_lessons').insert(row))}if(error){msg.textContent=error.message;return}msg.textContent='Lesson saved ✓';await loadCourseAdmin();selectCourse(currentCourse.id);setTimeout(closeLesson,350)});
C('#deleteLesson')?.addEventListener('click',async()=>{if(!editingLesson)return;if(!confirm(`Delete “${editingLesson.title}”?`))return;const{error}=await courseSb.from('nexora_lessons').delete().eq('id',editingLesson.id);if(error){C('#lessonMessage').textContent=error.message;return}await loadCourseAdmin();selectCourse(currentCourse.id);closeLesson()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLesson()});courseSb?.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')showCourseLogin()});checkCourseAdmin();