const ADMIN_CONFIG={url:'https://bcvtkdehflmqiyvloyiy.supabase.co',key:'sb_publishable_KgISTJ7-YKktjQXw3u0yuQ_KG6H1bFa'};
const adminSb=window.supabase?.createClient(ADMIN_CONFIG.url,ADMIN_CONFIG.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const A=(s,r=document)=>r.querySelector(s),AA=(s,r=document)=>[...r.querySelectorAll(s)];
const adminLogin=A('#adminLogin'),adminApp=A('#adminApp'),adminList=A('#adminList'),adminStatus=A('#adminStatus');
let adminRole=null,activeTab='students',students=[],enrollments=[],contacts=[],activeRecord=null;
const STATUS={students:['active','watch','paused','completed'],enrollments:['new','reviewing','contacted','approved','closed'],contacts:['new','reviewing','answered','closed']};
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function prettyDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return v||'—'}}
function duration(sec){const n=Math.max(0,Number(sec)||0);const h=Math.floor(n/3600),m=Math.floor((n%3600)/60);return h?`${h}h ${m}m`:`${m}m`}
function setAdminMessage(text=''){if(adminStatus)adminStatus.textContent=text}
async function checkAdmin(){if(!adminSb)return false;const{data:{session}}=await adminSb.auth.getSession();if(!session){showLogin();return false}const{data,error}=await adminSb.from('admin_users').select('role').eq('user_id',session.user.id).maybeSingle();if(error||!data){await adminSb.auth.signOut();showLogin('This account is not authorized for Nexora Admin.');return false}adminRole=data.role;A('#adminIdentity').textContent=`${session.user.email||'Admin'} · ${adminRole}`;adminLogin?.classList.add('hidden');adminApp?.classList.remove('hidden');await loadAll();return true}
function showLogin(message=''){adminApp?.classList.add('hidden');adminLogin?.classList.remove('hidden');if(A('#adminLoginMessage'))A('#adminLoginMessage').textContent=message}
A('#adminLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();const msg=A('#adminLoginMessage');if(msg)msg.textContent='Signing in…';const email=A('#adminEmail')?.value.trim(),password=A('#adminPassword')?.value||'';const{error}=await adminSb.auth.signInWithPassword({email,password});if(error){if(msg)msg.textContent=error.message;return}if(msg)msg.textContent='Checking admin access…';await checkAdmin()});
A('#adminLogout')?.addEventListener('click',async()=>{await adminSb.auth.signOut();location.reload()});
async function loadAll(){setAdminMessage('Loading admin data…');const[s,e,c]=await Promise.all([
  adminSb.from('nexora_portal_state').select('*').order('updated_at',{ascending:false}),
  adminSb.from('nexora_enrollments').select('*').order('created_at',{ascending:false}),
  adminSb.from('nexora_contacts').select('*').order('created_at',{ascending:false})
]);if(s.error||e.error||c.error){console.error(s.error||e.error||c.error);setAdminMessage('Could not load admin data. Check your admin permissions.');return}students=s.data||[];enrollments=e.data||[];contacts=c.data||[];renderMetrics();renderStatusOptions();renderList();setAdminMessage(`Updated ${new Date().toLocaleTimeString()}`)}
function currentData(){return activeTab==='students'?students:(activeTab==='enrollments'?enrollments:contacts)}
function renderMetrics(){A('#metricStudents').textContent=students.length;A('#metricEnrollments').textContent=enrollments.length;A('#metricContacts').textContent=contacts.length;const all=[...enrollments,...contacts];A('#metricNew').textContent=all.filter(x=>x.status==='new').length;A('#metricOpen').textContent=all.filter(x=>!['approved','answered','closed'].includes(x.status)).length}
function renderStatusOptions(){const sel=A('#adminStatusFilter'),edit=A('#adminEditStatus');const choices=STATUS[activeTab]||[];if(sel){const old=sel.value||'all';sel.innerHTML='<option value="all">All status</option>'+choices.map(s=>`<option value="${s}">${s}</option>`).join('');sel.value=choices.includes(old)?old:'all'}if(edit)edit.innerHTML=choices.map(s=>`<option value="${s}">${s}</option>`).join('')}
function recordStatus(r){return activeTab==='students'?(r.student_status||'active'):(r.status||'new')}
function recordText(r){if(activeTab==='students')return [r.display_name,r.email,r.student_status,r.note,(r.completed||[]).join(' ')].join(' ');if(activeTab==='enrollments')return [r.full_name,r.email,r.track,r.level,r.goal,r.status].join(' ');return [r.full_name,r.email,r.message,r.status].join(' ')}
function studentProgress(r){const done=Array.isArray(r.completed)?r.completed.filter(x=>String(x).startsWith('lesson-')).length:0;return `${done}/7 lessons · ${duration(r.total_seconds)}`}
function renderList(){if(!adminList)return;const q=(A('#adminSearch')?.value||'').trim().toLowerCase(),status=A('#adminStatusFilter')?.value||'all';const rows=currentData().filter(r=>(status==='all'||recordStatus(r)===status)&&(!q||recordText(r).toLowerCase().includes(q)));if(!rows.length){adminList.innerHTML='<div class="admin-empty">No matching records.</div>';return}adminList.innerHTML=rows.map(r=>{if(activeTab==='students'){const status=recordStatus(r);return `<article class="admin-row"><div class="admin-row-main"><strong>${esc(r.display_name||'Student')}</strong><span>${esc(r.email||'No email')}</span></div><div class="admin-row-meta"><b>${esc(studentProgress(r))}</b><span>Last visit: ${esc(r.last_visit||'—')} · Updated: ${prettyDate(r.updated_at)}</span></div><span class="admin-badge ${esc(status)}">${esc(status)}</span><button type="button" data-record-id="${esc(r.external_user_id)}">Open</button></article>`}const detail=activeTab==='enrollments'?(r.track||'Enrollment'):(r.message||'').slice(0,90),status=recordStatus(r);return `<article class="admin-row"><div class="admin-row-main"><strong>${esc(r.full_name)}</strong><span>${esc(r.email)}</span></div><div class="admin-row-meta"><b>${esc(detail)}</b><span>${prettyDate(r.created_at)}</span></div><span class="admin-badge ${esc(status)}">${esc(status)}</span><button type="button" data-record-id="${r.id}">Open</button></article>`}).join('');AA('[data-record-id]',adminList).forEach(btn=>btn.addEventListener('click',()=>openRecord(btn.dataset.recordId)))}
AA('.admin-tab').forEach(btn=>btn.addEventListener('click',()=>{AA('.admin-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');activeTab=btn.dataset.adminTab;A('#adminSearch').value='';renderStatusOptions();renderList()}));
A('#adminSearch')?.addEventListener('input',renderList);A('#adminStatusFilter')?.addEventListener('change',renderList);A('#adminRefresh')?.addEventListener('click',loadAll);
function detailItem(label,value){return `<div class="admin-detail"><small>${esc(label)}</small><div>${esc(value||'—')}</div></div>`}
function openRecord(id){activeRecord=currentData().find(r=>String(activeTab==='students'?r.external_user_id:r.id)===String(id));if(!activeRecord)return;const kicker=activeTab==='students'?'STUDENT':(activeTab==='enrollments'?'ENROLLMENT':'CONTACT');A('#adminModalKicker').textContent=kicker;A('#adminModalTitle').textContent=activeTab==='students'?(activeRecord.display_name||'Student'):(activeRecord.full_name||'Request');let fields;if(activeTab==='students'){const completed=Array.isArray(activeRecord.completed)?activeRecord.completed:[];fields=[['Email',activeRecord.email],['User ID',activeRecord.external_user_id],['Progress',studentProgress(activeRecord)],['Completed items',completed.join(', ')||'None yet'],['Streak',`${activeRecord.streak||1} day(s)`],['Last visit',activeRecord.last_visit],['Cloud updated',prettyDate(activeRecord.updated_at)],['Student note preview',(activeRecord.note||'').slice(0,500)||'—']]}else if(activeTab==='enrollments'){fields=[['Email',activeRecord.email],['Track',activeRecord.track],['Level',activeRecord.level],['Goal',activeRecord.goal],['Created',prettyDate(activeRecord.created_at)],['Updated',prettyDate(activeRecord.updated_at)]]}else{fields=[['Email',activeRecord.email],['Message',activeRecord.message],['Created',prettyDate(activeRecord.created_at)],['Updated',prettyDate(activeRecord.updated_at)]]}A('#adminDetailGrid').innerHTML=fields.map(x=>detailItem(...x)).join('');renderStatusOptions();A('#adminEditStatus').value=recordStatus(activeRecord);A('#adminEditNote').value=activeRecord.admin_note||'';A('#adminModalMessage').textContent='';A('#adminModal').classList.remove('hidden')}
function closeModal(){A('#adminModal')?.classList.add('hidden');activeRecord=null}A('#adminModalClose')?.addEventListener('click',closeModal);A('#adminCancel')?.addEventListener('click',closeModal);A('#adminModal')?.addEventListener('click',e=>{if(e.target===A('#adminModal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
A('#adminSave')?.addEventListener('click',async()=>{if(!activeRecord)return;const btn=A('#adminSave'),msg=A('#adminModalMessage');let table,key,payload;if(activeTab==='students'){table='nexora_portal_state';key={column:'external_user_id',value:activeRecord.external_user_id};payload={student_status:A('#adminEditStatus').value,admin_note:A('#adminEditNote').value.trim()}}else{table=activeTab==='enrollments'?'nexora_enrollments':'nexora_contacts';key={column:'id',value:activeRecord.id};payload={status:A('#adminEditStatus').value,admin_note:A('#adminEditNote').value.trim(),updated_at:new Date().toISOString()}}btn.disabled=true;btn.textContent='Saving…';msg.textContent='Saving changes…';const{error}=await adminSb.from(table).update(payload).eq(key.column,key.value);btn.disabled=false;btn.textContent='Save changes';if(error){msg.textContent=error.message;return}msg.textContent='Saved ✓';await loadAll();setTimeout(closeModal,550)});
function csvCell(v){const s=Array.isArray(v)?v.join('|'):String(v??'');return `"${s.replace(/"/g,'""')}"`}
A('#adminExport')?.addEventListener('click',()=>{const data=currentData();let cols;if(activeTab==='students')cols=['external_user_id','display_name','email','student_status','completed','total_seconds','today_seconds','last_visit','streak','admin_note','updated_at'];else if(activeTab==='enrollments')cols=['id','full_name','email','track','level','goal','status','admin_note','created_at','updated_at'];else cols=['id','full_name','email','message','status','admin_note','created_at','updated_at'];const csv=[cols.join(','),...data.map(r=>cols.map(c=>csvCell(r[c])).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`nexora-${activeTab}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)});
adminSb?.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')showLogin()});checkAdmin();