const ADMIN_CONFIG={url:'https://bcvtkdehflmqiyvloyiy.supabase.co',key:'sb_publishable_KgISTJ7-YKktjQXw3u0yuQ_KG6H1bFa'};
const adminSb=window.supabase?.createClient(ADMIN_CONFIG.url,ADMIN_CONFIG.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const A=(s,r=document)=>r.querySelector(s),AA=(s,r=document)=>[...r.querySelectorAll(s)];
const adminLogin=A('#adminLogin'),adminApp=A('#adminApp'),adminList=A('#adminList'),adminStatus=A('#adminStatus');
let adminRole=null,activeTab='students',students=[],prompts=[],enrollments=[],contacts=[],activeRecord=null,editingPrompt=null;
const STATUS={students:['active','watch','paused','completed'],prompts:['active','inactive'],enrollments:['new','reviewing','contacted','approved','closed'],contacts:['new','reviewing','answered','closed']};
const STUDENT_ADMIN_FIELDS='external_user_id,email,display_name,completed,total_seconds,today_seconds,time_date,last_visit,streak,updated_at,admin_status,admin_note,course_access,course_access_granted_at,niche,creator_goal,creator_level,preferred_language,bio';
function esc(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function prettyDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return v||'—'}}
function duration(sec){const n=Math.max(0,Number(sec)||0),h=Math.floor(n/3600),m=Math.floor((n%3600)/60);return h?`${h}h ${m}m`:`${m}m`}
function setAdminMessage(text=''){if(adminStatus)adminStatus.textContent=text}
async function checkAdmin(){if(!adminSb)return false;const{data:{session}}=await adminSb.auth.getSession();if(!session){showLogin();return false}const{data,error}=await adminSb.from('admin_users').select('role').eq('user_id',session.user.id).maybeSingle();if(error||!data){await adminSb.auth.signOut();showLogin('This account is not authorized for Nexora Admin.');return false}adminRole=data.role;A('#adminIdentity').textContent=`${session.user.email||'Admin'} · ${adminRole}`;adminLogin?.classList.add('hidden');adminApp?.classList.remove('hidden');await loadAll();return true}
function showLogin(message=''){adminApp?.classList.add('hidden');adminLogin?.classList.remove('hidden');if(A('#adminLoginMessage'))A('#adminLoginMessage').textContent=message}
A('#adminLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();const msg=A('#adminLoginMessage');if(msg)msg.textContent='Signing in…';const email=A('#adminEmail')?.value.trim(),password=A('#adminPassword')?.value||'';const{error}=await adminSb.auth.signInWithPassword({email,password});if(error){if(msg)msg.textContent=error.message;return}if(msg)msg.textContent='Checking admin access…';await checkAdmin()});
A('#adminLogout')?.addEventListener('click',async()=>{await adminSb.auth.signOut();location.reload()});
async function loadAll(){setAdminMessage('Loading admin data…');const[s,p,e,c]=await Promise.all([adminSb.from('nexora_portal_state').select(STUDENT_ADMIN_FIELDS).order('updated_at',{ascending:false}),adminSb.from('nexora_prompts').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:true}),adminSb.from('nexora_enrollments').select('*').order('created_at',{ascending:false}),adminSb.from('nexora_contacts').select('*').order('created_at',{ascending:false})]);if(s.error||p.error||e.error||c.error){console.error(s.error||p.error||e.error||c.error);setAdminMessage('Could not load admin data. Check your admin permissions.');return}students=s.data||[];prompts=p.data||[];enrollments=e.data||[];contacts=c.data||[];renderMetrics();renderStatusOptions();renderList();setAdminMessage(`Updated ${new Date().toLocaleTimeString()}`)}
function currentData(){return activeTab==='students'?students:activeTab==='prompts'?prompts:activeTab==='enrollments'?enrollments:contacts}
function renderMetrics(){A('#metricStudents').textContent=students.length;A('#metricPrompts').textContent=prompts.filter(x=>x.is_active).length;A('#metricEnrollments').textContent=enrollments.length;A('#metricContacts').textContent=contacts.length;A('#metricNew').textContent=[...enrollments,...contacts].filter(x=>x.status==='new').length}
function renderStatusOptions(){const sel=A('#adminStatusFilter'),edit=A('#adminEditStatus'),choices=STATUS[activeTab]||[];if(sel){const old=sel.value||'all';sel.innerHTML='<option value="all">All status</option>'+choices.map(s=>`<option value="${s}">${s}</option>`).join('');sel.value=choices.includes(old)?old:'all'}if(edit&&activeTab!=='prompts')edit.innerHTML=choices.map(s=>`<option value="${s}">${s}</option>`).join('');A('#adminNewPrompt')?.classList.toggle('hidden',activeTab!=='prompts')}
function recordStatus(r){if(activeTab==='students')return r.admin_status||'active';if(activeTab==='prompts')return r.is_active?'active':'inactive';return r.status||'new'}
function recordText(r){if(activeTab==='students')return [r.display_name,r.email,r.admin_status,r.course_access,r.niche,r.creator_goal,r.creator_level,r.preferred_language,r.bio,(r.completed||[]).join(' ')].join(' ');if(activeTab==='prompts')return [r.title,r.slug,r.category,r.prompt_text,r.image_url,r.is_active?'active':'inactive'].join(' ');if(activeTab==='enrollments')return [r.full_name,r.email,r.track,r.level,r.goal,r.status].join(' ');return [r.full_name,r.email,r.message,r.status].join(' ')}
function studentProgress(r){const done=Array.isArray(r.completed)?r.completed.filter(x=>String(x).startsWith('lesson:')||String(x).startsWith('lesson-')).length:0;return `${done} lessons · ${duration(r.total_seconds)} · ${r.course_access||'starter'} access`}
function renderList(){if(!adminList)return;const q=(A('#adminSearch')?.value||'').trim().toLowerCase(),status=A('#adminStatusFilter')?.value||'all';const rows=currentData().filter(r=>(status==='all'||recordStatus(r)===status)&&(!q||recordText(r).toLowerCase().includes(q)));if(!rows.length){adminList.innerHTML='<div class="admin-empty">No matching records.</div>';return}adminList.innerHTML=rows.map(r=>{if(activeTab==='students'){const st=recordStatus(r);return `<article class="admin-row"><div class="admin-row-main"><strong>${esc(r.display_name||'Student')}</strong><span>${esc(r.email||'No email')}</span></div><div class="admin-row-meta"><b>${esc(studentProgress(r))}</b><span>${esc(r.niche||'No niche yet')} · Updated ${prettyDate(r.updated_at)}</span></div><span class="admin-badge ${esc(st)}">${esc(st)}</span><button type="button" data-record-id="${esc(r.external_user_id)}">Open</button></article>`}if(activeTab==='prompts'){const st=recordStatus(r);return `<article class="admin-row prompt-row"><div class="admin-row-main"><strong>${esc(r.title)}</strong><span>${esc(r.slug)}</span></div><div class="admin-row-meta"><b>${esc(r.category)}</b><span>Sort ${esc(r.sort_order)} · ${prettyDate(r.updated_at)}</span></div><span class="admin-badge ${st}">${st}</span><button type="button" data-prompt-id="${r.id}">Edit</button></article>`}const detail=activeTab==='enrollments'?(r.track||'Enrollment'):(r.message||'').slice(0,90),st=recordStatus(r);return `<article class="admin-row"><div class="admin-row-main"><strong>${esc(r.full_name)}</strong><span>${esc(r.email)}</span></div><div class="admin-row-meta"><b>${esc(detail)}</b><span>${prettyDate(r.created_at)}</span></div><span class="admin-badge ${esc(st)}">${esc(st)}</span><button type="button" data-record-id="${r.id}">Open</button></article>`}).join('');AA('[data-record-id]',adminList).forEach(btn=>btn.addEventListener('click',()=>openRecord(btn.dataset.recordId)));AA('[data-prompt-id]',adminList).forEach(btn=>btn.addEventListener('click',()=>openPromptEditor(prompts.find(p=>String(p.id)===btn.dataset.promptId))))}
AA('.admin-tab').forEach(btn=>btn.addEventListener('click',()=>{AA('.admin-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');activeTab=btn.dataset.adminTab;A('#adminSearch').value='';renderStatusOptions();renderList()}));A('#adminSearch')?.addEventListener('input',renderList);A('#adminStatusFilter')?.addEventListener('change',renderList);A('#adminRefresh')?.addEventListener('click',loadAll);
function detailItem(label,value){return `<div class="admin-detail"><small>${esc(label)}</small><div>${esc(value||'—')}</div></div>`}
function openRecord(id){activeRecord=currentData().find(r=>String(activeTab==='students'?r.external_user_id:r.id)===String(id));if(!activeRecord||activeTab==='prompts')return;const isStudent=activeTab==='students',kicker=isStudent?'STUDENT':activeTab==='enrollments'?'ENROLLMENT':'CONTACT';A('#adminModalKicker').textContent=kicker;A('#adminModalTitle').textContent=isStudent?(activeRecord.display_name||'Student'):(activeRecord.full_name||'Request');let fields;if(isStudent){const completed=Array.isArray(activeRecord.completed)?activeRecord.completed:[];fields=[['Email',activeRecord.email],['Course access',activeRecord.course_access||'starter'],['Access granted',prettyDate(activeRecord.course_access_granted_at)],['Niche',activeRecord.niche],['Creator level',activeRecord.creator_level],['Language',activeRecord.preferred_language],['Creator goal',activeRecord.creator_goal],['Bio',activeRecord.bio],['Progress',studentProgress(activeRecord)],['Completed items',completed.join(', ')||'None yet'],['Streak',`${activeRecord.streak||1} day(s)`],['Last visit',activeRecord.last_visit],['Cloud updated',prettyDate(activeRecord.updated_at)]]}else if(activeTab==='enrollments'){fields=[['Email',activeRecord.email],['Track',activeRecord.track],['Level',activeRecord.level],['Goal',activeRecord.goal],['Created',prettyDate(activeRecord.created_at)],['Updated',prettyDate(activeRecord.updated_at)]]}else{fields=[['Email',activeRecord.email],['Message',activeRecord.message],['Created',prettyDate(activeRecord.created_at)],['Updated',prettyDate(activeRecord.updated_at)]]}A('#adminDetailGrid').innerHTML=fields.map(x=>detailItem(...x)).join('');renderStatusOptions();A('#adminEditStatus').value=recordStatus(activeRecord);A('#adminEditNote').value=activeRecord.admin_note||'';A('#adminCourseAccessWrap')?.classList.toggle('hidden',!isStudent);if(isStudent&&A('#adminCourseAccess'))A('#adminCourseAccess').value=activeRecord.course_access||'starter';A('#adminModalMessage').textContent='';A('#adminModal').classList.remove('hidden')}
function closeModal(){A('#adminModal')?.classList.add('hidden');A('#adminCourseAccessWrap')?.classList.add('hidden');activeRecord=null}A('#adminModalClose')?.addEventListener('click',closeModal);A('#adminCancel')?.addEventListener('click',closeModal);A('#adminModal')?.addEventListener('click',e=>{if(e.target===A('#adminModal'))closeModal()});
A('#adminSave')?.addEventListener('click',async()=>{if(!activeRecord)return;const btn=A('#adminSave'),msg=A('#adminModalMessage');let table,key,payload;if(activeTab==='students'){table='nexora_portal_state';key={column:'external_user_id',value:activeRecord.external_user_id};payload={admin_status:A('#adminEditStatus').value,course_access:A('#adminCourseAccess')?.value||'starter',admin_note:A('#adminEditNote').value.trim()}}else{table=activeTab==='enrollments'?'nexora_enrollments':'nexora_contacts';key={column:'id',value:activeRecord.id};payload={status:A('#adminEditStatus').value,admin_note:A('#adminEditNote').value.trim(),updated_at:new Date().toISOString()}}btn.disabled=true;btn.textContent='Saving…';msg.textContent='Saving changes…';const{error}=await adminSb.from(table).update(payload).eq(key.column,key.value);btn.disabled=false;btn.textContent='Save changes';if(error){msg.textContent=error.message;return}msg.textContent='Saved ✓';await loadAll();setTimeout(closeModal,450)});
function makeSlug(v){return String(v||'').trim().toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,160)}
function openPromptEditor(p=null){editingPrompt=p||null;A('#promptEditorTitle').textContent=p?'Edit prompt':'New prompt';A('#promptEditTitle').value=p?.title||'';A('#promptEditCategory').value=p?.category||'';A('#promptEditSlug').value=p?.slug||'';A('#promptEditImage').value=p?.image_url||'';A('#promptEditSort').value=p?.sort_order??100;A('#promptEditActive').value=String(p?.is_active??true);A('#promptEditText').value=p?.prompt_text||'';A('#promptEditorMessage').textContent='';A('#promptEditorDelete').classList.toggle('hidden',!p);A('#promptEditor').classList.remove('hidden')}
function closePromptEditor(){A('#promptEditor')?.classList.add('hidden');editingPrompt=null}A('#adminNewPrompt')?.addEventListener('click',()=>openPromptEditor());A('#promptEditorClose')?.addEventListener('click',closePromptEditor);A('#promptEditorCancel')?.addEventListener('click',closePromptEditor);A('#promptEditor')?.addEventListener('click',e=>{if(e.target===A('#promptEditor'))closePromptEditor()});
A('#promptEditorSave')?.addEventListener('click',async()=>{const btn=A('#promptEditorSave'),msg=A('#promptEditorMessage'),title=A('#promptEditTitle').value.trim(),category=A('#promptEditCategory').value.trim(),text=A('#promptEditText').value.trim();if(title.length<2||category.length<2||text.length<10){msg.textContent='Add a title, category and full prompt first.';return}const row={title,category,prompt_text:text,slug:makeSlug(A('#promptEditSlug').value||title),image_url:A('#promptEditImage').value.trim(),sort_order:Math.max(0,Number(A('#promptEditSort').value)||100),is_active:A('#promptEditActive').value==='true',updated_at:new Date().toISOString()};btn.disabled=true;btn.textContent='Saving…';let error;if(editingPrompt){({error}=await adminSb.from('nexora_prompts').update(row).eq('id',editingPrompt.id))}else{({error}=await adminSb.from('nexora_prompts').insert(row))}btn.disabled=false;btn.textContent='Save prompt';if(error){msg.textContent=error.message;return}msg.textContent='Prompt saved ✓';await loadAll();setTimeout(closePromptEditor,450)});
A('#promptEditorDelete')?.addEventListener('click',async()=>{if(!editingPrompt)return;const msg=A('#promptEditorMessage');if(!confirm(`Delete “${editingPrompt.title}”?`))return;const{error}=await adminSb.from('nexora_prompts').delete().eq('id',editingPrompt.id);if(error){msg.textContent=error.message;return}msg.textContent='Prompt deleted';await loadAll();setTimeout(closePromptEditor,350)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closePromptEditor()}});
function csvCell(v){const s=Array.isArray(v)?v.join('|'):String(v??'');return `"${s.replace(/"/g,'""')}"`}
A('#adminExport')?.addEventListener('click',()=>{const data=currentData();let cols;if(activeTab==='students')cols=['external_user_id','display_name','email','admin_status','course_access','course_access_granted_at','niche','creator_level','preferred_language','creator_goal','bio','completed','total_seconds','today_seconds','last_visit','streak','admin_note','updated_at'];else if(activeTab==='prompts')cols=['id','slug','title','category','prompt_text','image_url','is_active','sort_order','created_at','updated_at'];else if(activeTab==='enrollments')cols=['id','full_name','email','track','level','goal','status','admin_note','created_at','updated_at'];else cols=['id','full_name','email','message','status','admin_note','created_at','updated_at'];const csv=[cols.join(','),...data.map(r=>cols.map(c=>csvCell(r[c])).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`nexora-${activeTab}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)});
adminSb?.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')showLogin()});checkAdmin();