const promptAdminSb=window.nexoraSupabase;
const paState={items:[],selected:null};
const pa=id=>document.getElementById(id);
const paSafe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function paMsg(text,type='info'){pa('promptAdminMessage').textContent=text||'';pa('promptAdminMessage').dataset.type=type;}
async function requirePromptAdmin(){if(!promptAdminSb){location.href='login.html';return false;}const {data:{session}}=await promptAdminSb.auth.getSession();if(!session){location.href='login.html';return false;}const {data}=await promptAdminSb.from('profiles').select('role').eq('user_id',session.user.id).single();if(!data||data.role!=='admin'){pa('promptAdminGate').innerHTML='<span>ADMIN ACCESS</span><h1>Admin role required.</h1><p><a class="btn btn-primary" href="dashboard.html">Back to Dashboard</a></p>';return false;}pa('promptAdminGate').hidden=true;pa('promptAdminApp').hidden=false;return true;}
async function loadAdminPrompts(){const {data,error}=await promptAdminSb.from('prompts').select('*').order('sort_order').order('created_at');if(error)throw error;paState.items=data||[];renderAdminPrompts();}
function renderAdminPrompts(){pa('adminPromptList').innerHTML=paState.items.map(item=>`<button class="manager-item${paState.selected===item.id?' active':''}" data-id="${item.id}"><div><b>${paSafe(item.title)}</b><span>${paSafe(item.category)}</span></div><i>${item.published?'Published':'Hidden'}</i></button>`).join('')||'<div class="manager-item"><div><b>No prompts</b><span>Create your first prompt.</span></div></div>';pa('adminPromptList').querySelectorAll('[data-id]').forEach(btn=>btn.addEventListener('click',()=>editPrompt(btn.dataset.id)));}
function resetPrompt(){paState.selected=null;pa('promptAdminForm').reset();pa('promptId').value='';pa('promptSort').value='0';pa('promptPublished').checked=true;pa('deletePromptBtn').hidden=true;pa('promptEditorTitle').textContent='Create prompt';paMsg('');renderAdminPrompts();}
function editPrompt(id){const item=paState.items.find(x=>x.id===id);if(!item)return;paState.selected=id;pa('promptId').value=item.id;pa('promptTitle').value=item.title;pa('promptAdminCategory').value=item.category;pa('promptDescription').value=item.description||'';pa('promptText').value=item.prompt_text;pa('promptSort').value=item.sort_order;pa('promptPublished').checked=item.published;pa('deletePromptBtn').hidden=false;pa('promptEditorTitle').textContent='Edit prompt';paMsg('');renderAdminPrompts();}
async function savePrompt(e){e.preventDefault();const id=pa('promptId').value;const payload={title:pa('promptTitle').value.trim(),category:pa('promptAdminCategory').value.trim(),description:pa('promptDescription').value.trim(),prompt_text:pa('promptText').value.trim(),sort_order:Number(pa('promptSort').value)||0,published:pa('promptPublished').checked,updated_at:new Date().toISOString()};paMsg('Saving…');const res=id?await promptAdminSb.from('prompts').update(payload).eq('id',id):await promptAdminSb.from('prompts').insert(payload);if(res.error){paMsg(res.error.message,'error');return;}paMsg('Prompt saved.','success');await loadAdminPrompts();if(id)editPrompt(id);else resetPrompt();}
async function deletePrompt(){const id=pa('promptId').value;if(!id)return;if(!confirm('Delete this prompt?'))return;const {error}=await promptAdminSb.from('prompts').delete().eq('id',id);if(error){paMsg(error.message,'error');return;}resetPrompt();await loadAdminPrompts();}
async function initPromptAdmin(){pa('promptAdminLogout').addEventListener('click',async()=>{await promptAdminSb.auth.signOut();location.href='login.html';});if(!await requirePromptAdmin())return;pa('newPromptBtn').addEventListener('click',resetPrompt);pa('promptAdminForm').addEventListener('submit',savePrompt);pa('deletePromptBtn').addEventListener('click',deletePrompt);try{await loadAdminPrompts();resetPrompt();}catch(err){alert(err.message);}}
initPromptAdmin();