const managerSb=window.nexoraSupabase;
const mState={session:null,profile:null,courses:[],lessons:[],content:[],selectedCourse:null,selectedLesson:null};
const m=id=>document.getElementById(id);
const msafe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function msg(id,text,type='info'){const el=m(id);if(!el)return;el.textContent=text||'';el.dataset.type=type;}
async function requireAdmin(){if(!managerSb){location.href='login.html';return false;}const {data:{session}}=await managerSb.auth.getSession();if(!session){location.href='login.html';return false;}mState.session=session;const {data}=await managerSb.from('profiles').select('*').eq('user_id',session.user.id).single();if(!data||data.role!=='admin'){m('managerGate').innerHTML='<span>ADMIN ACCESS</span><h1>Admin role required.</h1><p><a class="btn btn-primary" href="dashboard.html">Back to Dashboard</a></p>';return false;}mState.profile=data;m('managerGate').hidden=true;m('managerApp').hidden=false;return true;}
async function loadManager(){const [c,l,ct]=await Promise.all([managerSb.from('courses').select('*').order('sort_order'),managerSb.from('lessons').select('*').order('course_slug').order('sort_order'),managerSb.from('lesson_content').select('*')]);if(c.error)throw c.error;if(l.error)throw l.error;if(ct.error)throw ct.error;mState.courses=c.data||[];mState.lessons=l.data||[];mState.content=ct.data||[];renderCourses();renderLessons();fillCourseSelect();}
function renderCourses(){m('courseManagerList').innerHTML=mState.courses.map(c=>`<button class="manager-item${mState.selectedCourse===c.slug?' active':''}" data-course="${msafe(c.slug)}"><div><b>${msafe(c.title)}</b><span>${msafe(c.category)} · ${msafe(c.slug)}</span></div><i>${c.published?'Published':'Hidden'}</i></button>`).join('')||'<div class="manager-item"><div><b>No courses</b><span>Create your first course.</span></div></div>';m('courseManagerList').querySelectorAll('[data-course]').forEach(btn=>btn.addEventListener('click',()=>editCourse(btn.dataset.course)));}
function renderLessons(){m('lessonManagerList').innerHTML=mState.lessons.map(l=>`<button class="manager-item${mState.selectedLesson===l.slug?' active':''}" data-lesson="${msafe(l.slug)}"><div><b>${msafe(l.title)}</b><span>${msafe(l.course_slug)} · ${l.duration_minutes} min</span></div><i>${l.is_free_preview?'Preview':l.published?'Published':'Hidden'}</i></button>`).join('')||'<div class="manager-item"><div><b>No lessons</b><span>Create your first lesson.</span></div></div>';m('lessonManagerList').querySelectorAll('[data-lesson]').forEach(btn=>btn.addEventListener('click',()=>editLesson(btn.dataset.lesson)));}
function fillCourseSelect(){const select=m('lessonCourse');const current=select.value;select.innerHTML=mState.courses.map(c=>`<option value="${msafe(c.slug)}">${msafe(c.title)}</option>`).join('');if(current&&mState.courses.some(c=>c.slug===current))select.value=current;}
function resetCourse(){mState.selectedCourse=null;m('courseForm').reset();m('courseOriginalSlug').value='';m('courseSlug').readOnly=false;m('courseSort').value='0';m('coursePublished').checked=true;m('courseEditorTitle').textContent='Create course';m('deleteCourseBtn').hidden=true;msg('courseMessage','');renderCourses();}
function editCourse(slug){const c=mState.courses.find(x=>x.slug===slug);if(!c)return;mState.selectedCourse=slug;m('courseOriginalSlug').value=c.slug;m('courseSlug').value=c.slug;m('courseSlug').readOnly=true;m('courseTitle').value=c.title;m('courseCategory').value=c.category;m('courseSummary').value=c.summary||'';m('courseSort').value=c.sort_order;m('coursePublished').checked=c.published;m('courseEditorTitle').textContent='Edit course';m('deleteCourseBtn').hidden=false;msg('courseMessage','');renderCourses();}
async function saveCourse(e){e.preventDefault();const original=m('courseOriginalSlug').value;const payload={slug:m('courseSlug').value.trim(),title:m('courseTitle').value.trim(),category:m('courseCategory').value.trim(),summary:m('courseSummary').value.trim(),sort_order:Number(m('courseSort').value)||0,published:m('coursePublished').checked};msg('courseMessage','Saving…');let res;if(original)res=await managerSb.from('courses').update({...payload,slug:original}).eq('slug',original);else res=await managerSb.from('courses').insert(payload);if(res.error){msg('courseMessage',res.error.message,'error');return;}msg('courseMessage','Course saved.','success');await loadManager();if(original)editCourse(original);else resetCourse();}
async function deleteCourse(){const slug=m('courseOriginalSlug').value;if(!slug)return;if(!confirm('Delete this course and all of its lessons?'))return;const {error}=await managerSb.from('courses').delete().eq('slug',slug);if(error){msg('courseMessage',error.message,'error');return;}resetCourse();await loadManager();}
function resetLesson(){mState.selectedLesson=null;m('lessonForm').reset();m('lessonOriginalSlug').value='';m('lessonSlug').readOnly=false;m('lessonDuration').value='10';m('lessonSort').value='0';m('lessonPublished').checked=true;m('lessonPreview').checked=false;m('lessonEditorTitle').textContent='Create lesson';m('deleteLessonBtn').hidden=true;fillCourseSelect();msg('lessonMessage','');renderLessons();}
function editLesson(slug){const l=mState.lessons.find(x=>x.slug===slug);if(!l)return;const ct=mState.content.find(x=>x.lesson_slug===slug)||{};mState.selectedLesson=slug;m('lessonOriginalSlug').value=l.slug;m('lessonCourse').value=l.course_slug;m('lessonSlug').value=l.slug;m('lessonSlug').readOnly=true;m('lessonTitle').value=l.title;m('lessonSummary').value=l.summary||'';m('lessonDuration').value=l.duration_minutes;m('lessonSort').value=l.sort_order;m('lessonPreview').checked=l.is_free_preview;m('lessonPublished').checked=l.published;m('lessonBody').value=ct.body||'';m('lessonTask').value=ct.action_task||'';m('lessonEditorTitle').textContent='Edit lesson';m('deleteLessonBtn').hidden=false;msg('lessonMessage','');renderLessons();}
async function saveLesson(e){e.preventDefault();const original=m('lessonOriginalSlug').value;const slug=original||m('lessonSlug').value.trim();const payload={slug,course_slug:m('lessonCourse').value,title:m('lessonTitle').value.trim(),summary:m('lessonSummary').value.trim(),duration_minutes:Math.max(1,Number(m('lessonDuration').value)||10),sort_order:Number(m('lessonSort').value)||0,is_free_preview:m('lessonPreview').checked,published:m('lessonPublished').checked};msg('lessonMessage','Saving…');const lessonRes=original?await managerSb.from('lessons').update(payload).eq('slug',original):await managerSb.from('lessons').insert(payload);if(lessonRes.error){msg('lessonMessage',lessonRes.error.message,'error');return;}const contentRes=await managerSb.from('lesson_content').upsert({lesson_slug:slug,body:m('lessonBody').value.trim(),action_task:m('lessonTask').value.trim(),updated_at:new Date().toISOString()},{onConflict:'lesson_slug'});if(contentRes.error){msg('lessonMessage',contentRes.error.message,'error');return;}msg('lessonMessage','Lesson saved.','success');await loadManager();editLesson(slug);}
async function deleteLesson(){const slug=m('lessonOriginalSlug').value;if(!slug)return;if(!confirm('Delete this lesson and its progress/content records?'))return;const {error}=await managerSb.from('lessons').delete().eq('slug',slug);if(error){msg('lessonMessage',error.message,'error');return;}resetLesson();await loadManager();}
async function initManager(){m('managerLogout').addEventListener('click',async()=>{await managerSb.auth.signOut();location.href='login.html';});if(!await requireAdmin())return;m('managerRefresh').addEventListener('click',()=>loadManager().catch(err=>alert(err.message)));m('newCourseBtn').addEventListener('click',resetCourse);m('newLessonBtn').addEventListener('click',resetLesson);m('courseForm').addEventListener('submit',saveCourse);m('lessonForm').addEventListener('submit',saveLesson);m('deleteCourseBtn').addEventListener('click',deleteCourse);m('deleteLessonBtn').addEventListener('click',deleteLesson);try{await loadManager();resetCourse();resetLesson();}catch(err){alert(err.message);}}
initManager();