const menuToggle=document.getElementById('menuToggle');const navLinks=document.getElementById('navLinks');menuToggle?.addEventListener('click',()=>navLinks?.classList.toggle('open'));document.querySelectorAll('#navLinks a').forEach(a=>a.addEventListener('click',()=>navLinks?.classList.remove('open')));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));

const chips=[...document.querySelectorAll('.filter-chip')];const promptCards=[...document.querySelectorAll('.prompt-card')];chips.forEach(chip=>chip.addEventListener('click',()=>{chips.forEach(x=>x.classList.remove('active'));chip.classList.add('active');const f=chip.dataset.filter;promptCards.forEach(card=>card.style.display=(f==='all'||card.dataset.category===f)?'block':'none')}));
const promptModal=document.getElementById('promptModal');const modalTitle=document.getElementById('modalTitle');const modalCategory=document.getElementById('modalCategory');const modalPrompt=document.getElementById('modalPrompt');promptCards.forEach(card=>card.addEventListener('click',()=>{if(!promptModal)return;modalTitle.textContent=card.dataset.title||'Prompt';modalCategory.textContent=(card.dataset.category||'PROMPT').replaceAll('-',' ').toUpperCase();modalPrompt.textContent=card.dataset.prompt||'Prompt content will be added here.';promptModal.classList.add('open');document.body.style.overflow='hidden'}));function closePromptModal(){promptModal?.classList.remove('open');document.body.style.overflow=''}document.getElementById('closePromptModal')?.addEventListener('click',closePromptModal);promptModal?.addEventListener('click',e=>{if(e.target===promptModal)closePromptModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePromptModal()});

const SUPABASE_URL='https://vlnhsdsncqcugfpjjlas.supabase.co';const SUPABASE_KEY='sb_publishable_S-YSKMI32JyEoPb1cMJL_Q_1_0jKBn0';let sb=null;if(window.supabase){sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
const authPage=document.getElementById('authPage');const portal=document.getElementById('portal');const portalName=document.getElementById('portalName');const portalEmail=document.getElementById('portalEmail');function showPortal(session){const user=session?.user;if(!authPage||!portal)return;if(user){authPage.style.display='none';portal.classList.add('show');const meta=user.user_metadata||{};if(portalName)portalName.textContent=meta.full_name||meta.name||user.email?.split('@')[0]||'Student';if(portalEmail)portalEmail.textContent=user.email||''}else{authPage.style.display='grid';portal.classList.remove('show')}}
async function initAuth(){if(!sb)return;const{data}=await sb.auth.getSession();showPortal(data.session);sb.auth.onAuthStateChange((_event,session)=>showPortal(session))}initAuth();
document.getElementById('googleLogin')?.addEventListener('click',async()=>{if(!sb)return;await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:'https://lensbykai-bit.github.io/NexoraTikTok/learn.html'}})});
document.getElementById('emailLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;const email=document.getElementById('loginEmail').value.trim();const password=document.getElementById('loginPassword').value;const msg=document.getElementById('loginMessage');if(msg)msg.textContent='Signing in…';const{error}=await sb.auth.signInWithPassword({email,password});if(msg)msg.textContent=error?error.message:'Signed in.'});
document.getElementById('logoutPortal')?.addEventListener('click',async()=>{if(sb)await sb.auth.signOut()});

const tabButtons=[...document.querySelectorAll('.tab-btn')];const tabPanels=[...document.querySelectorAll('.tab-panel')];tabButtons.forEach(btn=>btn.addEventListener('click',()=>{tabButtons.forEach(x=>x.classList.remove('active'));tabPanels.forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.tab)?.classList.add('active')}));
const noteArea=document.getElementById('noteArea');if(noteArea){noteArea.value=localStorage.getItem('nexora_student_note')||'';document.getElementById('saveNote')?.addEventListener('click',()=>{localStorage.setItem('nexora_student_note',noteArea.value);const msg=document.getElementById('noteSaved');if(msg){msg.textContent='Saved ✓';setTimeout(()=>msg.textContent='',1500)}})}

document.querySelectorAll('[data-complete]').forEach(btn=>btn.addEventListener('click',()=>{btn.textContent='Completed ✓';btn.disabled=true}));