const VERIFY_CONFIG={url:'https://bcvtkdehflmqiyvloyiy.supabase.co/functions/v1/certificate-verify',apikey:'sb_publishable_KgISTJ7-YKktjQXw3u0yuQ_KG6H1bFa'};
const V=s=>document.querySelector(s);
function ve(v=''){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function vd(v){if(!v)return '—';try{return new Intl.DateTimeFormat(undefined,{dateStyle:'long'}).format(new Date(v))}catch{return String(v)}}
function normalizeCode(v=''){return String(v).trim().toUpperCase().replace(/\s+/g,'')}
function showVerifyLoading(code){V('#verifyResult').innerHTML=`<div class="verify-card"><div class="verify-mark">N</div><h2>Checking certificate…</h2><p>${ve(code)}</p></div>`}
function showVerifyInvalid(code,status='not_found'){const text=status==='revoked'?'This certificate is no longer active.':'No active Nexora certificate was found with this code.';V('#verifyResult').innerHTML=`<div class="verify-card verify-invalid"><span class="verify-badge">Not verified</span><h2>Certificate not valid</h2><p>${ve(text)}</p><div class="verify-data"><div><small>Certificate code</small><strong>${ve(code)}</strong></div><div><small>Status</small><strong>${ve(status.replaceAll('_',' '))}</strong></div></div></div>`}
function showVerifyValid(c){V('#verifyResult').innerHTML=`<div class="verify-card verify-valid"><span class="verify-badge">Verified certificate</span><h2>${ve(c.display_name||'Nexora Student')}</h2><p>This certificate is active in the Nexora Digital Creator Academy records.</p><div class="verify-data"><div><small>Certificate code</small><strong>${ve(c.certificate_code)}</strong></div><div><small>Status</small><strong>Verified · Active</strong></div><div><small>Completed lessons</small><strong>${ve(c.lesson_count)}</strong></div><div><small>Issued</small><strong>${ve(vd(c.issued_at))}</strong></div></div></div>`}
async function verifyCode(code){const btn=V('#verifyButton');showVerifyLoading(code);if(btn){btn.disabled=true;btn.textContent='Checking…'}try{const res=await fetch(VERIFY_CONFIG.url,{method:'POST',headers:{'Content-Type':'application/json',apikey:VERIFY_CONFIG.apikey},body:JSON.stringify({code})});const data=await res.json().catch(()=>({}));if(!res.ok){showVerifyInvalid(code,'invalid_code');return}if(data.valid&&data.certificate)showVerifyValid(data.certificate);else showVerifyInvalid(code,data.status||'not_found')}catch(err){console.warn('Certificate verify:',err);V('#verifyResult').innerHTML='<div class="verify-card verify-invalid"><span class="verify-badge">Unavailable</span><h2>Verification unavailable</h2><p>Please try again in a moment.</p></div>'}finally{if(btn){btn.disabled=false;btn.textContent='Verify'}}}
V('#verifyForm')?.addEventListener('submit',e=>{e.preventDefault();const code=normalizeCode(V('#verifyCode').value);V('#verifyCode').value=code;if(!/^NEX-[A-F0-9]{12}$/.test(code)){showVerifyInvalid(code||'—','invalid_code');return}const u=new URL(location.href);u.searchParams.set('code',code);history.replaceState(null,'',u);verifyCode(code)});
const initial=normalizeCode(new URLSearchParams(location.search).get('code')||'');if(initial){V('#verifyCode').value=initial;if(/^NEX-[A-F0-9]{12}$/.test(initial))verifyCode(initial)}